# NumPy
Table of Contents
1. Converting a List to an array
2. Arange Function
3. Multidimensional Array
4. Size Function
5. Shape Function
6. Dtype Function
7. Ndim Function
8. Zeros and Ones Function
9. Eye Function
10. Empty Function
11. Random Functions:
-----a) np.random.rand
-----b) np.random.randint
-----c) np.random.randn
12. Reshape function
13. Linspace Function
14. Flatten Function
15. Logspace Function
16. Copy Function
17. arr.max() , arr.min() , arr.sum() functions
18. Seed function
19. Sorting in numpy array
20. Mathematical Operation in Numpy
-----a) Addition
-----b) Substraction
-----c) Multiplication
-----d) Division
-----e) Matrix Multiplication
-----f) Power
21. Percentile Function
22. Mean, Variance and Standard Deviation
23. Filtering an numpy array
24. Transposing an array
25. Where function
26. Merging Arrays
-----a) Using Concatenate
-----b) Using vstack and hstack
27. Splitting Arrays
28. Turning Pictures into Numpy arrays

In [1]:
import numpy as np 

# 1.Converting a list to array

In [3]:
lst=[1,2,3,4]
print(type(lst))
arr=np.array(lst)
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
arr=np.array(lst,ndmin=1)
arr

array([1, 2, 3, 4])

In [6]:
arr=np.array(lst,ndmin=2)
arr

array([[1, 2, 3, 4]])

In [7]:
arr=np.array(lst,ndmin=5)
arr

array([[[[[1, 2, 3, 4]]]]])

# 2. Arrange function
The arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval.
The interval mentioned is half-opened i.e. [Start, Stop) 

In [9]:
arr=np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

# 3.Multidimensional Array

In [16]:
arr=np.array([[1,2,3,],[4,5,6],[7,8,9,]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 4.Size Function
In Python, numpy.size() function count the number of elements along a given axis (0 - Rows | 1 - Columns)

In [19]:
arr=np.array([[1,2,3,],[4,5,6],[7,8,9,],[1,2,3]])
print("Total:",arr.size)
print("Total:",np.size(arr,0))
print("Total:",np.size(arr,1))

Total: 12
Total: 4
Total: 3


# 5. Shape Function
The shape of an array can be defined as the number of elements in each dimension.
Dimension is the number of indices or subscripts, that we require in order to specify an individual element of an array.

In [22]:
arr=np.array([[1,2,3,],[4,5,6],[7,8,9,],[1,2,3]])
print((np.size(arr,0),np.size(arr,1)))
arr.shape



(4, 3)


(4, 3)

# 6. Dtype Function
Every ndarray has an associated data type (dtype) object. This data type object (dtype) informs us about the layout of the array. This means it gives us information about:

Type of the data (integer, float, Python object, etc.)
Size of the data (number of bytes)
The byte order of the data (little-endian or big-endian)
If the data type is a sub-array, what is its shape and data type?

In [25]:
arr1=np.array([1,2,3,1,2,3])
arr2=np.array([1.2,2.3,1,2,])

print(arr1.dtype)
print(arr2.dtype)

int32
float64


# 7. Ndim Function
numpy.ndarray.ndim() function return the number of dimensions of an array.

In [28]:
arr1=np.array([1,2,3,1,2,3])
arr2=np.array([[1,2,3],[1,2,3]])
arr3=np.array(arr1,ndmin=3)


print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


8. Zeros  Function
The numpy.zeros() function returns a new array of given shape and type, with zeros. Syntax:

numpy.zeros(shape, dtype = None)

In [32]:
np.zeros(shape=(3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# Ones Function
The numpy.ones() function returns a new array of given shape and type, with ones.

Syntax: numpy.ones(shape, dtype = None

In [35]:
np.ones(shape=(3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

# 9. Eye  Function
The eye tool returns a 2-D array with  1’s as the diagonal and  0’s elsewhere. 
The diagonal can be main, upper, or lower depending on the optional parameter k.

In [42]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# 10. Empty  Function
Return am empty array of given shape and type

In [59]:
np.empty(shape=(2,2))

array([[1., 0.],
       [0., 1.]])

# 11. Random  Functions
a) np.random.rand
The numpy.random.rand() function creates an array of specified shape and fills it with random values.

In [62]:
np.random.rand(3,4)

array([[0.69748647, 0.62635733, 0.02985235, 0.00940895],
       [0.40837616, 0.51784195, 0.97175949, 0.66998187],
       [0.91428427, 0.8273991 , 0.4859609 , 0.88053307]])

# b) np.random.randint
numpy.random.randint() is one of the function for doing random sampling in numpy. It returns an array of specified shape 
and fills it with random integers from low (inclusive) to high (exclusive), i.e. in the interval [low, high).

In [67]:
np.random.randint(low=1,high=10,size=20)

array([6, 2, 1, 4, 9, 8, 5, 5, 6, 2, 6, 8, 4, 6, 8, 2, 7, 4, 3, 6])

# c) np.random.randn
The numpy.random.randn() function creates an array of specified shape 
and fills it with random values as per standard normal distribution.

In [92]:
np.random.randn(100)

array([ 0.81659843,  1.15520034,  0.38119892,  1.98087212,  0.52894996,
        1.4280081 ,  0.01039765, -0.7501333 , -0.20034531, -2.38677547,
        1.42946465, -1.8987148 , -2.12290112,  1.66148623, -0.44996255,
        0.87266439, -0.48628335, -0.6485922 , -0.18413108, -0.02246625,
       -1.81746352,  1.05760437,  0.90670505,  0.54139048,  0.93158727,
        0.06713677,  1.42703436, -0.50271105, -0.68191312,  0.05752476,
        1.53034936,  0.12962321,  0.9042837 , -0.82808829,  0.4577167 ,
       -2.96952853,  0.60243956, -0.12085865,  0.90789958,  0.57112133,
       -0.08251448,  1.97894179, -0.12472158,  0.46064573, -0.37203245,
        0.90107999, -2.01876765, -0.45298722,  0.5035148 ,  0.38644927,
        0.21428028, -0.59697587,  1.75317835,  0.96559524,  1.1495625 ,
       -0.8515081 ,  1.71337907, -1.13011992,  0.33051475, -0.22102343,
       -2.03867102,  0.0999234 ,  1.66137747, -0.43548648, -1.25557607,
       -0.05075617, -0.22699124, -0.65341116,  2.11253705,  0.12

In [96]:
import matplotlib.pyplot as plt
plt.hist(np.random.randn(1000),bins=10)

(array([  1.,   2.,  20.,  92., 232., 276., 254.,  97.,  20.,   6.]),
 array([-4.29178729, -3.51859613, -2.74540497, -1.97221381, -1.19902265,
        -0.42583149,  0.34735967,  1.12055083,  1.89374199,  2.66693315,
         3.44012431]),
 <BarContainer object of 10 artists>)

# 12. Reshape function - will not alter the original data
The numpy.reshape() function shapes an array without changing the data of the array.<br> It should be noted
that the product if the rows and columns should be same 

In [112]:
arr=np.random.randint(1,15,(3,4))
print(arr.shape)
arr=arr.reshape(4,3)
print(arr.shape)

(3, 4)
(4, 3)



# 13. Linspace  Function
The numpy.linspace() function returns number spaces evenly w.r.t interval. Similar to numpy.arange() function but instead of step it uses sample number.

Parameters :

-> start : [optional] start of interval range. By default start = 0
-> stop : end of interval range
-> restep : If True, return (samples, step). By default restep = False
-> num : [int, optional] No. of samples to generate
-> dtype : type of output array

In [114]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# 14. Flatten  Function
ndarray.flatten() function return a 
copy of the array collapsed into one dimension.

In [117]:
arr=np.random.randint(1,15,(3,4))
print(arr.shape)
arr=arr.flatten()
print(arr.shape)
print(arr)

(3, 4)
(12,)
[11  8  6  7  2  6  3  3  7 14 10 12]


# 15. Logspace  Function
The numpy.logspace() function returns number spaces evenly w.r.t interval on a log scale.

Parameters :

-> start : [float] start(base ** start) of interval range.
-> stop : [float] end(base ** stop) of interval range
-> endpoint : [boolean, optional]If True, stop is the last sample. By default, True
-> num : [int, optional] No. of samples to generate
-> base : [float, optional] Base of log scale. By default, equals 10.0
-> dtype : type of output array

In [124]:
print(np.logspace(2,4,10))
print('-'*20)
print(np.logspace(2,4,10, base = 2))

[  100.           166.81005372   278.25594022   464.15888336
   774.26368268  1291.54966501  2154.43469003  3593.8136638
  5994.84250319 10000.        ]
--------------------
[ 4.          4.66611616  5.44316     6.34960421  7.4069977   8.64047791
 10.0793684  11.75787594 13.71590373 16.        ]


# 16. Copy function
If we normally use the equals sign then the **id** of both the numpy array will be same,
so we need to use to copy function

In [137]:
arr1=np.random.randint(1,15,10)
arr2=arr1
print(arr1,id(arr1))
print(arr2,id(arr2))
print("-"*20)
arr1=np.random.randint(1,15,10)
arr2=np.copy(arr1)
print(arr1,id(arr1))
print(arr2,id(arr2))
#id is different 

[ 3 10  7  4  6  1  9  6  3  6] 1789679772240
[ 3 10  7  4  6  1  9  6  3  6] 1789679772240
--------------------
[14 14  3  4  8  3  6  6  5  3] 1789679775888
[14 14  3  4  8  3  6  6  5  3] 1789671301520


# 17. arr.max() ,  arr.min() ,     arr.sum() functions
arr.max() will give us the maximum element present in the array
arr.min() will give us the minimun element present in the array
arr.sum() will give us the sum of all the elements present in the array

In [144]:

arr = np.random.randint(1,30,(3,5))

print('-'*20)
print(arr)
print('-'*20)

print('MAX : ', arr.max())
print('MIN : ', arr.min())
print('SUM : ', arr.sum())


--------------------
[[ 6 17 24  1 14]
 [ 7 29  5  6 19]
 [23 28 16  7 18]]
--------------------
MAX :  29
MIN :  1
SUM :  220



# We can use the axis parameter to get the max, min and sum of a particular column or row

axis=0 is for the column
axis=1 is for the row

In [147]:
arr = np.random.randint(1,30,(3,5))

print('-'*20)
print(arr)
print('-'*20)


--------------------
[[18 27 11 18 25]
 [21 25 14  6 26]
 [11 16 27 21 25]]
--------------------


# For columns


In [150]:
print('MAX : ', arr.max(axis = 0))
print('MIN : ', arr.min(axis = 0))
print('SUM : ', arr.sum(axis = 0))

MAX :  [21 27 27 21 26]
MIN :  [11 16 11  6 25]
SUM :  [50 68 52 45 76]


# For Rows

In [153]:
print('MAX : ', arr.max(axis = 1))
print('MIN : ', arr.min(axis = 1))
print('SUM : ', arr.sum(axis = 1))

MAX :  [27 26 27]
MIN :  [11  6 11]
SUM :  [ 99  92 100]


# 18. Seed Function
random() function is used to generate random numbers in Python. Not actually random, rather this is used to generate pseudo-random numbers. That implies that these randomly generated numbers can be determined. random() function generates numbers for some values. This value is also called seed value.

Syntax : random.seed( l, version )<br>

Parameter :

l : Any seed value used to produce a random number.
version : A integer used to specify how to convert l in a integer.

In [156]:
np.random.seed(3)

arr = np.random.randint(1,10,(3,5))

arr

array([[9, 4, 9, 9, 1],
       [6, 4, 6, 8, 7],
       [1, 5, 8, 9, 2]])

# 19. Sorting Function
numpy.sort() : This function returns a sorted copy of an array.

Parameters :

arr : Array to be sorted.
axis : Axis along which we need array to be started.
order : This argument specifies which fields to compare first.
kind : [‘quicksort’{default}, ‘mergesort’, ‘heapsort’]Sorting algorithm.

In [159]:
np.random.seed(3)
arr = np.random.randint(1,10,(3,5))


print('-'*15)
print(arr)
print('-'*15)
print(np.sort(arr, axis = 1))
print('-'*15)
print(np.sort(arr, axis = 0))
print('-'*15)

arr = np.reshape(np.sort(arr.flatten()), arr.shape)
print(arr)
print('-'*15)


---------------
[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
---------------
[[1 4 9 9 9]
 [4 6 6 7 8]
 [1 2 5 8 9]]
---------------
[[1 4 6 8 1]
 [6 4 8 9 2]
 [9 5 9 9 7]]
---------------
[[1 1 2 4 4]
 [5 6 6 7 8]
 [8 9 9 9 9]]
---------------


# we can choose which type of sort we want to perform

In [170]:
print(np.sort(arr, axis = 0,kind='mergesort'))


[[1 1 2 4 4]
 [5 6 6 7 8]
 [8 9 9 9 9]]


# 20)Mathematical operatin

# a) Addition

In [175]:
np.random.seed(3)

arr = np.random.randint(1,10,(3,5))

print('-' * 15)
print(arr)
print('-' * 15)
print(arr + 1)
print('-' * 15)

---------------
[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
---------------
[[10  5 10 10  2]
 [ 7  5  7  9  8]
 [ 2  6  9 10  3]]
---------------


# b)subtraction

In [178]:
print('-' * 15)
print(arr)
print('-' * 15)
print(arr - 1)
print('-' * 15)

---------------
[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
---------------
[[8 3 8 8 0]
 [5 3 5 7 6]
 [0 4 7 8 1]]
---------------


# c)Multiplication

In [181]:
print('-' * 15)
print(arr)
print('-' * 15)
print(arr * 2)
print('-' * 15)


---------------
[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
---------------
[[18  8 18 18  2]
 [12  8 12 16 14]
 [ 2 10 16 18  4]]
---------------


# d)Division

In [184]:
print('-' * 15)
print(arr)
print('-' * 15)
print(arr / 2)
print('-' * 15)


---------------
[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
---------------
[[4.5 2.  4.5 4.5 0.5]
 [3.  2.  3.  4.  3.5]
 [0.5 2.5 4.  4.5 1. ]]
---------------


# e) Matrix Multiplication
For Matrix Multiplication we either use the 

dot function or
the @ symbol

In [187]:
np.random.seed(3)

arr1 = np.random.randint(1,10,(2,2))
arr2 = np.random.randint(1,10,(2,2))

print(arr1.dot(arr2))
print('-'*12)
print(arr1@arr2)

[[ 25  78]
 [ 45 108]]
------------
[[ 25  78]
 [ 45 108]]


# f)power

In [194]:
print(arr)
print('-'*15)
print(arr**2)

[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
---------------
[[81 16 81 81  1]
 [36 16 36 64 49]
 [ 1 25 64 81  4]]


# 21. Percentile Function
numpy.percentile()function used to compute the nth percentile 
of the given data (array elements) along the specified axis.

In [197]:

np.random.seed(3)

arr = np.random.randint(1,10,10)
print(arr)

arr = np.sort(arr)
print(arr)

print(np.percentile(arr, 50))

[9 4 9 9 1 6 4 6 8 7]
[1 4 4 6 6 7 8 9 9 9]
6.5


# 22. Mean, Variance and Standard deviation
In NumPy, we can compute the mean, standard deviation, and variance of a given array along the second axis by two approaches first is by using inbuilt functions and second is by the formulas of the mean, standard deviation, and variance.

Using numpy.mean(), numpy.std(), numpy.var()

In [200]:
arr = np.random.randint(1,10,10)

print(arr)
print(arr.mean())
print(arr.var())
print(arr.std())

[1 5 8 9 2 7 3 3 2 4]
4.4
6.839999999999999
2.6153393661244038


# 23. Filtering an numpy array

In [221]:
arr=np.arange(1,15)
print(arr)
print(arr>5)
print(arr[arr<5])



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[False False False False False  True  True  True  True  True  True  True
  True  True]
[1 2 3 4]


We can store this into a new variable if we need this filtered array

In [224]:
arr2 = arr[arr < 5] 
print(arr2)

[1 2 3 4]


If we want to replace all the values above 5 with 10 we can even do that

In [227]:
arr[arr > 5] = 10
arr

array([ 1,  2,  3,  4,  5, 10, 10, 10, 10, 10, 10, 10, 10, 10])

# 24 Transposing an array
With the help of Numpy ndarray.T object, we can make a Transpose of an array having dimension greater than or equal to 2.
here we are converting rows from columns and columns from rows

In [235]:
arr=np.random.randint(1,20,(3,5))
print(arr)
print('-'*20)
print(arr.T)

[[ 1 17 19 19 12]
 [ 1 14  6 17  2]
 [18 19  3  5  9]]
--------------------
[[ 1  1 18]
 [17 14 19]
 [19  6  3]
 [19 17  5]
 [12  2  9]]


# 25. Where function 
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

Syntax :numpy.where(condition[, x, y]) Parameters: condition : When True, yield x, otherwise yield y. x, y : Values from which to choose. x, y and condition need to be broadcastable to some shape.

Returns: out : [ndarray or tuple of ndarrays] If both x and y are specified, the output array contains elements of x where condition is True, and elements from y elsewhere.

If only condition is given, return the tuple condition.nonzero(), the indices where condition is True.

In [240]:
arr=np.random.randint(1,20,10)
arr

array([17, 10,  2, 16, 12, 11, 17, 17, 13,  5])

#
So now if we are having an even number let's convert it into 100 and the ones which are odd we leave it to the way it is

In [251]:
print(arr)

print(np.where(arr%2==0, 'even',arr))
print(np.where(arr%2!=0, 'odd',arr))

arr1 = np.where(arr%2==0, 'even',arr)
arr1 = np.where(arr%2!=0, 'odd',arr1)

print(arr1)

[17 10  2 16 12 11 17 17 13  5]
['17' 'even' 'even' 'even' 'even' '11' '17' '17' '13' '5']
['odd' '10' '2' '16' '12' 'odd' 'odd' 'odd' 'odd' 'odd']
['odd' 'even' 'even' 'even' 'even' 'odd' 'odd' 'odd' 'odd' 'odd']


# 26. Merging Arrays
# a) Concatenate
We can perform the concatenation operation using the concatenate() function. With this function, arrays are concatenated either row-wise or column-wise, given that they have 
equal rows or columns respectively. Column-wise concatenation can be done by equating axis to 1 as an argument in the function.

In [255]:
arr1 = np.random.randint(1,10,(2,4))
arr2 = np.random.randint(1,10,(2,4))

print(arr1)
print('-'*15)
print(arr2)

print('-'*30)
print(np.concatenate((arr1,arr2), axis = 0))
print('-'*30)
print(np.concatenate((arr1,arr2), axis = 1))

[[4 1 9 3]
 [8 3 2 4]]
---------------
[[3 5 2 3]
 [3 8 4 5]]
------------------------------
[[4 1 9 3]
 [8 3 2 4]
 [3 5 2 3]
 [3 8 4 5]]
------------------------------
[[4 1 9 3 3 5 2 3]
 [8 3 2 4 3 8 4 5]]


# b) Vstack and Hstack
numpy.hstack() function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.

In [258]:
arr1 = np.random.randint(1,10,(2,4))
arr2 = np.random.randint(1,10,(2,4))

print(arr1)
print('-'*15)
print(arr2)
print('-'*15)

print(np.hstack((arr1,arr2)))

[[2 7 8 2]
 [1 1 6 9]]
---------------
[[5 9 9 4]
 [5 3 6 5]]
---------------
[[2 7 8 2 5 9 9 4]
 [1 1 6 9 5 3 6 5]]


# 27. Splitting Arrays

In [265]:
arr=np.random.randint(1,10,(4,4))
print(arr)

[[9 2 6 4]
 [7 2 4 8]
 [5 1 9 5]
 [8 9 6 7]]


numpy.vsplit() function split an array into multiple sub-arrays vertically (row-wise). vsplit is equivalent
to split with axis=0 (default), the array is always split along the first axis regardless of the array dimension.

In [268]:
np.hsplit(arr, 2)

[array([[9, 2],
        [7, 2],
        [5, 1],
        [8, 9]]),
 array([[6, 4],
        [4, 8],
        [9, 5],
        [6, 7]])]

# 28. Turning Pics into Numpy arrays

This is picture we are having right here

Once we can turn this picture into an numpy array we can perform operations on that and pass the array even for some machine learning algorithms which will be benefitial for us

We will be using imread function here which belongs from the matplotlib class

In [274]:
from matplotlib.image import imread

img = imread('GFG.png')

img.shape

(607, 1000, 3)